x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  contest_db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - contest_postgresql:/var/lib/postgresql/data
    networks:
      - backend

  submission_db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: submission_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - submission_postgresql:/var/lib/postgresql/data
    networks:
      - backend

  #  Judge0
  judge0-server:
    image: judge0/judge0:1.13.1
    hostname: judge0-server
    container_name: judge0-server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0-workers:
    image: judge0/judge0:1.13.1
    hostname: judge0-workers
    container_name: judge0-workers
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0-db:
    image: postgres:16.2
    env_file: judge0.conf
    hostname: judge0-db
    container_name: judge0-db
    volumes:
      - judge0-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0-redis:
    image: redis:7.2.4
    hostname: judge0-redis
    container_name: judge0-redis
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - judge0


volumes:
  contest_postgresql: { }
  submission_postgresql: { }
  judge0-data: { }

networks:
  backend: { }
  judge0: { }