global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: contest-service
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8080" ]

  - job_name: submission-service
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8090" ]
