spring:
  application:
    name: submission-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.31.120:5433/submission_db
server:
  port: 8090

app:
  judge0-api-base-url: http://192.168.31.120:2358
  retry:
    retry-max-attempts: 3
    retry-min-time: 1s
    jitter-factor: 0.75
