spring:
  application:
    name: submission-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/submission_db
  cache:
    cache-names: "languages-cache"
    caffeine:
      spec: "expireAfterWrite=24h"
server:
  port: 8090

app:
  judge0-api-base-url: http://localhost:2358
  scheduling:
    number-of-threads: 4
  retry:
    retry-max-attempts: 3
    retry-min-time: 1s
    jitter-factor: 0.75
