spring:
  application:
    name: submission-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${SUBMISSION_POSTGRES_HOST}:${SUBMISSION_POSTGRES_PORT}/submission_db
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cache:
    cache-names: "languages-cache"
    caffeine:
      spec: "expireAfterWrite=24h"
server:
  port: 8090
  error:
    include-stacktrace: never
    include-path: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  yandex-cloud:
    access-key-id: ${YANDEX_CLOUD_S3_ACCESS_KEY_ID}
    secret-access-key: ${YANDEX_CLOUD_S3_SECRET_ACCESS_KEY}
    submission-source-code-bucket-name: ${SUBMISSION_SOURCE_CODE_BUCKET_NAME}
    test-archive-bucket-name: ${TEST_ARCHIVE_BUCKET_NAME}
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
  judge0-api-base-url: ${JUDGE0_API_BASE_URL}
  scheduling:
    number-of-threads: 4
  retry:
    retry-max-attempts: 3
    retry-min-time: 1s
    jitter-factor: 0.75
  rabbit-mq:
    submission-queue-name: ${SUBMISSION_QUEUE_NAME}
    submission-dead-letter-queue-name: ${SUBMISSION_DEAD_LETTER_QUEUE_NAME}
    is-durable: false
