{
 "title": "T-Code",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": "contest-service, submission-service"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$service_name\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$service_name\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total published messages for last 15 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(rabbitmq_published_total{job=\"$service_name\"}[15m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Consumed messages for last 15 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(rabbitmq_consumed_total{job=\"$service_name\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx http response code percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~'4..'}[3m])) / sum(rate(http_server_requests_seconds_count[3m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx http response code percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~'5..'}[3m])) / sum(rate(http_server_requests_seconds_count[3m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"$service_name\"}[15m])) / sum(rate(http_server_requests_seconds_count{job=\"$service_name\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}