spring:
  application:
    name: contest-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/contest_db
server:
  port: 8080
