name: Contest Service Build

on:
  pull_request:
    paths:
      - .github/workflows/contest-service-workflow.yaml
      - contest-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make gradlew executable
        working-directory: contest-service
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        working-directory: contest-service
        run: ./gradlew build -x checkstyleMain -x checkstyleTest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: contest-service-jar
          path: contest-service/contest-service-0.0.1-SNAPSHOT.jar

      - id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/contest-service/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          title: Code Coverage

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make gradlew executable
        working-directory: contest-service
        run: chmod +x ./gradlew

      - run: ./gradlew checkstyleMain
        working-directory: contest-service

  docker:
    name: docker-build-push
    runs-on: ubuntu-latest
    needs: [build, checkstyle]

    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: contest-service-jar
          path: ./build/libs

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: contest-service
          push: true
          tags: ghcr.io/daniil-vl/contest-service:latest